branch-defaults:
  default:
    environment: udagram-apii-dev
    group_suffix: null
global:
  application_name: udagram-apii
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 14
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
